import { useEffect, useState, type ReactNode } from 'react';
import { AlertTriangle, BatteryCharging, CheckCircle2, FileText, Pencil, Plane, Plus, Trash2, Wrench, XCircle } from 'lucide-react';
import { getDocumentExpiryStatus, getManualFlightMinutes, toLocalDateKey, type AssetKind, type AssetPassport, type BatteryAsset, type DocumentRecord, type DroneAsset, type FleetReadiness, type IncidentRecord, type MaintenanceTask, type ManualFlightEntry } from '../domain/fleet';

type AssetOption = { kind: AssetKind; id: string; label: string };
type AssetLink = Pick<MaintenanceTask, 'assetKind' | 'assetId'>;

function AssetSelect({ assets, value, onChange }: { assets: AssetOption[]; value: string; onChange: (value: string) => void }) {
  return <select className="form-input" value={value} onChange={(event) => onChange(event.target.value)}><option value="">Без привязки</option>{assets.map((asset) => <option value={`${asset.kind}:${asset.id}`} key={`${asset.kind}:${asset.id}`}>{asset.label}</option>)}</select>;
}

function parseAsset(value: string): AssetLink {
  const [assetKind, assetId] = value.split(':') as [AssetKind | undefined, string | undefined];
  return assetKind && assetId ? { assetKind, assetId } : {};
}

function assetValue(item: AssetLink) {
  return item.assetKind && item.assetId ? `${item.assetKind}:${item.assetId}` : '';
}

export function FleetView({ drones, flights, onAddDrone, onSavePassport }: { drones: DroneAsset[]; flights: ManualFlightEntry[]; onAddDrone: () => void; onSavePassport: (kind: AssetKind, id: string, passport: AssetPassport) => void }) {
  return <>
    <div className="section-actions"><button className="upload-button" onClick={onAddDrone}><Plane size={16} />Добавить дрон</button><span>Паспорт заполняется вручную и хранится только в этом браузере.</span></div>
    <section className="table-grid">{drones.map((drone) => { const manualMinutes = getManualFlightMinutes(flights, drone.id); return <AssetCard key={drone.id} icon={<Plane size={18} />} title={drone.name} subtitle={drone.model} facts={[["Ручной налёт", manualMinutes ? `${manualMinutes} мин` : 'Нет записей'], ['Серийный номер', drone.passport?.serialNumber ?? 'Не указан'], ['Владелец', drone.passport?.owner ?? 'Не указан']]} passport={drone.passport} onSave={(passport) => onSavePassport('drone', drone.id, passport)} />; })}</section>
  </>;
}

export function BatteriesView({ batteries, onAddBattery, onSavePassport }: { batteries: BatteryAsset[]; onAddBattery: () => void; onSavePassport: (kind: AssetKind, id: string, passport: AssetPassport) => void }) {
  return <>
    <div className="section-actions"><button className="upload-button" onClick={onAddBattery}><BatteryCharging size={16} />Добавить батарею</button><span>Паспорт батареи ведётся вручную; техническая оценка не подменяется записями.</span></div>
    <section className="table-grid">{batteries.map((battery) => <AssetCard key={battery.id} icon={<BatteryCharging size={18} />} title={battery.label} subtitle="Паспорт батареи" facts={[["Циклы", battery.cycles === null ? 'Не указаны' : String(battery.cycles)], ['Серийный номер', battery.passport?.serialNumber ?? 'Не указан'], ['Дата приобретения', battery.passport?.acquiredOn ?? 'Не указана']]} passport={battery.passport} onSave={(passport) => onSavePassport('battery', battery.id, passport)} />)}</section>
  </>;
}

function AssetCard({ icon, title, subtitle, facts, passport, onSave }: { icon: ReactNode; title: string; subtitle: string; facts: string[][]; passport?: AssetPassport; onSave: (passport: AssetPassport) => void }) {
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState<AssetPassport>(passport ?? {});
  useEffect(() => setForm(passport ?? {}), [passport]);
  return <article className="panel entity-card operational-card">
    <div><p className="eyebrow">{subtitle}</p><h2>{title}</h2><span className="status-pill status-pill--warning">Данные введены вручную</span></div>
    <div className="entity-stats">{facts.map(([key, value]) => <span key={key}>{key}<b>{value}</b></span>)}</div>
    <button className="secondary-action" onClick={() => setOpen(!open)}>{icon} {open ? 'Скрыть паспорт' : 'Заполнить паспорт'}</button>
    {open && <form className="compact-form" onSubmit={(event) => { event.preventDefault(); onSave(form); setOpen(false); }}>
      <label>Серийный номер<input className="form-input" value={form.serialNumber ?? ''} onChange={(event) => setForm({ ...form, serialNumber: event.target.value })} /></label>
      <label>Учётный / регистрационный номер<input className="form-input" value={form.registrationNumber ?? ''} onChange={(event) => setForm({ ...form, registrationNumber: event.target.value })} /></label>
      <label>Владелец<input className="form-input" value={form.owner ?? ''} onChange={(event) => setForm({ ...form, owner: event.target.value })} /></label>
      <label>Дата приобретения<input className="form-input" type="date" value={form.acquiredOn ?? ''} onChange={(event) => setForm({ ...form, acquiredOn: event.target.value })} /></label>
      <label>Примечание<textarea className="form-input" value={form.note ?? ''} onChange={(event) => setForm({ ...form, note: event.target.value })} /></label>
      <button className="upload-button" type="submit">Сохранить паспорт</button>
    </form>}
  </article>;
}

export function MaintenanceView({ drones, batteries, flights, tasks, incidents, documents, readiness, onAddTask, onUpdateTask, onRemoveTask, onAddIncident, onUpdateIncident, onRemoveIncident, onAddDocument, onUpdateDocument, onRemoveDocument }: { drones: DroneAsset[]; batteries: BatteryAsset[]; flights: ManualFlightEntry[]; tasks: MaintenanceTask[]; incidents: IncidentRecord[]; documents: DocumentRecord[]; readiness: FleetReadiness; onAddTask: (input: Omit<MaintenanceTask, 'id' | 'createdAt' | 'completedAt' | 'status'>) => void; onUpdateTask: (id: string, update: Partial<Omit<MaintenanceTask, 'id' | 'createdAt' | 'completedAt'>>) => void; onRemoveTask: (id: string) => void; onAddIncident: (input: Omit<IncidentRecord, 'id' | 'createdAt' | 'resolvedAt' | 'status'>) => void; onUpdateIncident: (id: string, update: Partial<Omit<IncidentRecord, 'id' | 'createdAt' | 'resolvedAt'>>) => void; onRemoveIncident: (id: string) => void; onAddDocument: (input: Omit<DocumentRecord, 'id' | 'createdAt'>) => void; onUpdateDocument: (id: string, update: Partial<Omit<DocumentRecord, 'id' | 'createdAt'>>) => void; onRemoveDocument: (id: string) => void }) {
  const assets: AssetOption[] = [...drones.map((item) => ({ kind: 'drone' as const, id: item.id, label: `Дрон · ${item.name}` })), ...batteries.map((item) => ({ kind: 'battery' as const, id: item.id, label: `Батарея · ${item.label}` }))];
  const [task, setTask] = useState({ title: '', dueDate: '', asset: '', responsible: '', note: '' });
  const [incident, setIncident] = useState({ title: '', occurredOn: toLocalDateKey(), asset: '', flightId: '', severity: 'warning' as IncidentRecord['severity'], description: '' });
  const [document, setDocument] = useState({ title: '', documentType: 'Страховка', expiresOn: '', asset: '', reference: '' });
  const label = (kind?: AssetKind, id?: string) => assets.find((asset) => asset.kind === kind && asset.id === id)?.label ?? 'Без привязки';
  const flightLabel = (id?: string) => flights.find((flight) => flight.id === id) ? `${flights.find((flight) => flight.id === id)?.flightDate} · ${flights.find((flight) => flight.id === id)?.purpose}` : undefined;
  return <>
    <section className={`panel readiness-summary readiness-summary--${readiness.status}`}><div><p className="eyebrow">Готовность флота</p><h2>{readiness.label}</h2><p>Статус отражает только внесённые задачи, события, сроки и полноту ручных чек-листов; это не автоматический допуск к полёту.</p></div><ul>{readiness.facts.map((fact) => <li key={fact}>{fact}</li>)}</ul></section>
    <section className="operations-grid">
      <article className="panel"><p className="eyebrow">Обслуживание</p><h2>Новая задача</h2><form className="compact-form" onSubmit={(event) => { event.preventDefault(); onAddTask({ ...parseAsset(task.asset), title: task.title, dueDate: task.dueDate || undefined, responsible: task.responsible || undefined, note: task.note || undefined }); setTask({ title: '', dueDate: '', asset: '', responsible: '', note: '' }); }}><label>Что сделать<input required className="form-input" value={task.title} onChange={(event) => setTask({ ...task, title: event.target.value })} /></label><label>Срок<input className="form-input" type="date" value={task.dueDate} onChange={(event) => setTask({ ...task, dueDate: event.target.value })} /></label><label>Ответственный<input className="form-input" value={task.responsible} onChange={(event) => setTask({ ...task, responsible: event.target.value })} /></label><AssetSelect assets={assets} value={task.asset} onChange={(asset) => setTask({ ...task, asset })} /><label>Примечание<textarea className="form-input" value={task.note} onChange={(event) => setTask({ ...task, note: event.target.value })} /></label><button className="upload-button"><Plus size={16} />Добавить задачу</button></form></article>
      <article className="panel"><p className="eyebrow">События и наблюдения</p><h2>Зафиксировать событие</h2><form className="compact-form" onSubmit={(event) => { event.preventDefault(); onAddIncident({ ...parseAsset(incident.asset), title: incident.title, occurredOn: incident.occurredOn, severity: incident.severity, flightId: incident.flightId || undefined, description: incident.description || undefined }); setIncident({ title: '', occurredOn: toLocalDateKey(), asset: '', flightId: '', severity: 'warning', description: '' }); }}><label>Кратко<input required className="form-input" value={incident.title} onChange={(event) => setIncident({ ...incident, title: event.target.value })} /></label><label>Дата<input className="form-input" type="date" value={incident.occurredOn} onChange={(event) => setIncident({ ...incident, occurredOn: event.target.value })} /></label><select className="form-input" value={incident.severity} onChange={(event) => setIncident({ ...incident, severity: event.target.value as IncidentRecord['severity'] })}><option value="info">Наблюдение</option><option value="warning">Требует внимания</option><option value="critical">Критично</option></select><AssetSelect assets={assets} value={incident.asset} onChange={(asset) => setIncident({ ...incident, asset })} /><label>Связать с ручным вылетом<select className="form-input" value={incident.flightId} onChange={(event) => setIncident({ ...incident, flightId: event.target.value })}><option value="">Не связывать</option>{flights.map((flight) => <option key={flight.id} value={flight.id}>{flight.flightDate} · {flight.purpose}</option>)}</select></label><label>Описание<textarea className="form-input" value={incident.description} onChange={(event) => setIncident({ ...incident, description: event.target.value })} /></label><button className="upload-button"><AlertTriangle size={16} />Сохранить событие</button></form></article>
      <article className="panel"><p className="eyebrow">Документы</p><h2>Учёт срока</h2><form className="compact-form" onSubmit={(event) => { event.preventDefault(); onAddDocument({ ...parseAsset(document.asset), title: document.title, documentType: document.documentType, expiresOn: document.expiresOn || undefined, reference: document.reference || undefined }); setDocument({ title: '', documentType: 'Страховка', expiresOn: '', asset: '', reference: '' }); }}><label>Название<input required className="form-input" value={document.title} onChange={(event) => setDocument({ ...document, title: event.target.value })} /></label><label>Тип<input className="form-input" value={document.documentType} onChange={(event) => setDocument({ ...document, documentType: event.target.value })} /></label><label>Действует до<input className="form-input" type="date" value={document.expiresOn} onChange={(event) => setDocument({ ...document, expiresOn: event.target.value })} /></label><AssetSelect assets={assets} value={document.asset} onChange={(asset) => setDocument({ ...document, asset })} /><label>Где хранится / номер<textarea className="form-input" value={document.reference} onChange={(event) => setDocument({ ...document, reference: event.target.value })} /></label><button className="upload-button"><FileText size={16} />Добавить документ</button></form></article>
    </section>
    <section className="operations-list-grid">
      <RecordList title="Задачи обслуживания" empty="Задач пока нет." items={tasks} icon={<Wrench size={17} />} render={(item) => <TaskRecord item={item} assets={assets} onUpdate={(update) => onUpdateTask(item.id, update)} onRemove={() => onRemoveTask(item.id)} />} />
      <RecordList title="События и наблюдения" empty="Событий пока нет." items={incidents} icon={<AlertTriangle size={17} />} render={(item) => <IncidentRecordCard item={item} assets={assets} flights={flights} flightLabel={flightLabel(item.flightId)} onUpdate={(update) => onUpdateIncident(item.id, update)} onRemove={() => onRemoveIncident(item.id)} />} />
      <RecordList title="Документы и сроки" empty="Документы пока не добавлены." items={documents} icon={<FileText size={17} />} render={(item) => <DocumentRecordCard item={item} assets={assets} onUpdate={(update) => onUpdateDocument(item.id, update)} onRemove={() => onRemoveDocument(item.id)} />} />
    </section>
  </>;
}

function TaskRecord({ item, assets, onUpdate, onRemove }: { item: MaintenanceTask; assets: AssetOption[]; onUpdate: (update: Partial<Omit<MaintenanceTask, 'id' | 'createdAt' | 'completedAt'>>) => void; onRemove: () => void }) {
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ title: item.title, dueDate: item.dueDate ?? '', asset: assetValue(item), responsible: item.responsible ?? '', note: item.note ?? '', completionNote: item.completionNote ?? '' });
  useEffect(() => setForm({ title: item.title, dueDate: item.dueDate ?? '', asset: assetValue(item), responsible: item.responsible ?? '', note: item.note ?? '', completionNote: item.completionNote ?? '' }), [item]);
  const statusLabel = item.status === 'completed' ? 'Выполнено' : item.status === 'in_progress' ? 'В работе' : item.status === 'cancelled' ? 'Отменено' : 'Открыто';
  return <><strong>{item.title}</strong><p>{assets.find((asset) => `${asset.kind}:${asset.id}` === assetValue(item))?.label ?? 'Без привязки'} · {item.dueDate ? `срок ${item.dueDate}` : 'без срока'}{item.responsible ? ` · ${item.responsible}` : ''}</p><small>{statusLabel}{item.completionNote ? ` · ${item.completionNote}` : ''}</small>{editing ? <form className="compact-form record-form" onSubmit={(event) => { event.preventDefault(); onUpdate({ ...parseAsset(form.asset), title: form.title, dueDate: form.dueDate || undefined, responsible: form.responsible || undefined, note: form.note || undefined, completionNote: form.completionNote || undefined }); setEditing(false); }}><label>Название<input required className="form-input" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Срок<input className="form-input" type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /></label><label>Ответственный<input className="form-input" value={form.responsible} onChange={(event) => setForm({ ...form, responsible: event.target.value })} /></label><AssetSelect assets={assets} value={form.asset} onChange={(asset) => setForm({ ...form, asset })} /><label>Примечание<textarea className="form-input" value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} /></label>{item.status === 'completed' && <label>Результат<textarea className="form-input" value={form.completionNote} onChange={(event) => setForm({ ...form, completionNote: event.target.value })} /></label>}<button className="text-action">Сохранить</button></form> : <div className="record-actions">{item.status === 'open' && <button className="text-action" onClick={() => onUpdate({ status: 'in_progress' })}><Wrench size={15} />В работу</button>}{item.status !== 'completed' && item.status !== 'cancelled' && <button className="text-action" onClick={() => { const completionNote = window.prompt('Краткий результат выполнения', item.completionNote ?? ''); if (completionNote !== null) onUpdate({ status: 'completed', completionNote }); }}><CheckCircle2 size={15} />Выполнить</button>}{item.status !== 'completed' && item.status !== 'cancelled' && <button className="text-action" onClick={() => onUpdate({ status: 'cancelled' })}><XCircle size={15} />Отменить</button>}<button className="text-action" onClick={() => setEditing(true)}><Pencil size={15} />Изменить</button><button className="text-action text-action--danger" onClick={onRemove}><Trash2 size={15} />Удалить</button></div>}</>;
}

function IncidentRecordCard({ item, assets, flights, flightLabel, onUpdate, onRemove }: { item: IncidentRecord; assets: AssetOption[]; flights: ManualFlightEntry[]; flightLabel?: string; onUpdate: (update: Partial<Omit<IncidentRecord, 'id' | 'createdAt' | 'resolvedAt'>>) => void; onRemove: () => void }) {
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ title: item.title, occurredOn: item.occurredOn, asset: assetValue(item), flightId: item.flightId ?? '', severity: item.severity, description: item.description ?? '', resolutionNote: item.resolutionNote ?? '' });
  useEffect(() => setForm({ title: item.title, occurredOn: item.occurredOn, asset: assetValue(item), flightId: item.flightId ?? '', severity: item.severity, description: item.description ?? '', resolutionNote: item.resolutionNote ?? '' }), [item]);
  return <><strong>{item.title}</strong><p>{assets.find((asset) => `${asset.kind}:${asset.id}` === assetValue(item))?.label ?? 'Без привязки'} · {item.occurredOn} · {item.description ?? 'без описания'}{flightLabel ? ` · вылет: ${flightLabel}` : ''}</p><small>{item.status === 'resolved' ? `Закрыто${item.resolutionNote ? ` · ${item.resolutionNote}` : ''}` : item.severity === 'critical' ? 'Критичное событие' : item.severity === 'warning' ? 'Требует внимания' : 'Открыто'}</small>{editing ? <form className="compact-form record-form" onSubmit={(event) => { event.preventDefault(); onUpdate({ ...parseAsset(form.asset), title: form.title, occurredOn: form.occurredOn, flightId: form.flightId || undefined, severity: form.severity, description: form.description || undefined, resolutionNote: form.resolutionNote || undefined }); setEditing(false); }}><label>Кратко<input required className="form-input" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Дата<input className="form-input" type="date" value={form.occurredOn} onChange={(event) => setForm({ ...form, occurredOn: event.target.value })} /></label><select className="form-input" value={form.severity} onChange={(event) => setForm({ ...form, severity: event.target.value as IncidentRecord['severity'] })}><option value="info">Наблюдение</option><option value="warning">Требует внимания</option><option value="critical">Критично</option></select><AssetSelect assets={assets} value={form.asset} onChange={(asset) => setForm({ ...form, asset })} /><label>Ручной вылет<select className="form-input" value={form.flightId} onChange={(event) => setForm({ ...form, flightId: event.target.value })}><option value="">Не связывать</option>{flights.map((flight) => <option key={flight.id} value={flight.id}>{flight.flightDate} · {flight.purpose}</option>)}</select></label><label>Описание<textarea className="form-input" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label>{item.status === 'resolved' && <label>Как закрыто<textarea className="form-input" value={form.resolutionNote} onChange={(event) => setForm({ ...form, resolutionNote: event.target.value })} /></label>}<button className="text-action">Сохранить</button></form> : <div className="record-actions">{item.status === 'open' && <button className="text-action" onClick={() => { const resolutionNote = window.prompt('Как закрыто событие', item.resolutionNote ?? ''); if (resolutionNote !== null) onUpdate({ status: 'resolved', resolutionNote }); }}><CheckCircle2 size={15} />Закрыть</button>}{item.status === 'resolved' && <button className="text-action" onClick={() => onUpdate({ status: 'open' })}>Открыть снова</button>}<button className="text-action" onClick={() => setEditing(true)}><Pencil size={15} />Изменить</button><button className="text-action text-action--danger" onClick={onRemove}><Trash2 size={15} />Удалить</button></div>}</>;
}

function DocumentRecordCard({ item, assets, onUpdate, onRemove }: { item: DocumentRecord; assets: AssetOption[]; onUpdate: (update: Partial<Omit<DocumentRecord, 'id' | 'createdAt'>>) => void; onRemove: () => void }) {
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ title: item.title, documentType: item.documentType, expiresOn: item.expiresOn ?? '', asset: assetValue(item), reference: item.reference ?? '' });
  useEffect(() => setForm({ title: item.title, documentType: item.documentType, expiresOn: item.expiresOn ?? '', asset: assetValue(item), reference: item.reference ?? '' }), [item]);
  return <><strong>{item.title}</strong><p>{item.documentType} · {assets.find((asset) => `${asset.kind}:${asset.id}` === assetValue(item))?.label ?? 'Без привязки'}{item.reference ? ` · ${item.reference}` : ''}</p><small>{documentExpiryLabel(item)}</small>{editing ? <form className="compact-form record-form" onSubmit={(event) => { event.preventDefault(); onUpdate({ ...parseAsset(form.asset), title: form.title, documentType: form.documentType, expiresOn: form.expiresOn || undefined, reference: form.reference || undefined }); setEditing(false); }}><label>Название<input required className="form-input" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Тип<input className="form-input" value={form.documentType} onChange={(event) => setForm({ ...form, documentType: event.target.value })} /></label><label>Действует до<input className="form-input" type="date" value={form.expiresOn} onChange={(event) => setForm({ ...form, expiresOn: event.target.value })} /></label><AssetSelect assets={assets} value={form.asset} onChange={(asset) => setForm({ ...form, asset })} /><label>Где хранится / номер<textarea className="form-input" value={form.reference} onChange={(event) => setForm({ ...form, reference: event.target.value })} /></label><button className="text-action">Сохранить</button></form> : <div className="record-actions"><button className="text-action" onClick={() => setEditing(true)}><Pencil size={15} />Изменить</button><button className="text-action text-action--danger" onClick={onRemove}><Trash2 size={15} />Удалить</button></div>}</>;
}

function RecordList<T extends { id: string }>({ title, empty, items, icon, render }: { title: string; empty: string; items: T[]; icon: ReactNode; render: (item: T) => ReactNode }) {
  return <section className="panel operational-list"><div className="panel-heading"><div><p className="eyebrow">Учёт</p><h2>{title}</h2></div><span className="status-pill status-pill--warning">{items.length}</span></div>{items.length ? items.map((item) => <div className="list-row" key={item.id}><span className="row-status row-status--warning">{icon}</span><div>{render(item)}</div></div>) : <p className="empty-state">{empty}</p>}</section>;
}

function documentExpiryLabel(document: DocumentRecord) {
  if (!document.expiresOn) return 'Срок не указан';
  const status = getDocumentExpiryStatus(document);
  if (status === 'expired') return `Просрочен с ${document.expiresOn}`;
  if (status === 'expires_soon') return `Истекает ${document.expiresOn}`;
  return `Действует до ${document.expiresOn}`;
}
